<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>it.unibo.tecweb</groupId>
  <artifactId>ShopMood_Project_Id</artifactId>
  <packaging>war</packaging>
  <version>0.0.1-SNAPSHOT</version>
  <name>ShopMood_Project</name>
  <url>http://maven.apache.org</url>
  <properties>
	<jackson.version>3.0.0</jackson.version>
  	<maven.compiler.source>19</maven.compiler.source> <!-- Java version -->
  	<maven.compiler.target>19</maven.compiler.target> <!-- Java version -->
  	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  	<tomcat.server>C:\Users\albam\Desktop\apache-tomcat-9.0.112</tomcat.server> <!-- Aggiornare -->
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-csv</artifactId>
    <version>1.10.0</version>
</dependency>
 <dependency>
    <groupId>tools.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>${jackson.version}</version>
 </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>4.0.1</version>  <!-- The one used by Tomcat 9x -->
      <scope>provided</scope>   <!-- will not be included in the war -->
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.13.2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <build>
    <finalName>ShopMood</finalName>
    <plugins>
	  <plugin>
		  <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
      </plugin>
      <plugin>
           <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-war-plugin</artifactId>
           <version>3.4.0</version>
      </plugin>
	  <!-- CONFIGURATION to start TOMCAT in EXISTING mode -->
	  <plugin>
	    <groupId>org.codehaus.cargo</groupId>
  	    <artifactId>cargo-maven3-plugin</artifactId>
        <version>1.10.10</version>
  	    <configuration>
          <container>
            <containerId>tomcat9x</containerId>
            <type>installed</type>
            <log>${project.build.directory}/cargo.log</log>
            <logLevel>debug</logLevel>
            <home>${tomcat.server}</home>
          </container>
          <configuration>
			<type>existing</type>
			<home>${tomcat.server}</home>
            <properties>
			  <cargo.host>localhost</cargo.host>
              <cargo.servlet.port>8080</cargo.servlet.port>
              <cargo.logging>high</cargo.logging>
            </properties>
          </configuration>
          <deployables>
            <deployable>
              <location>${project.build.directory}/${project.build.finalName}.${project.packaging}</location>
              <type>war</type>
            </deployable>
          </deployables>
         </configuration>
	  </plugin>
	  <!-- CONFIGURATION to start TOMCAT in EMBEDDED mode -->
	  <!--<plugin>
	    <groupId>org.codehaus.cargo</groupId>
  	    <artifactId>cargo-maven3-plugin</artifactId>
        <version>1.10.10</version>
  	    <configuration>
          <container>
            <containerId>tomcat9x</containerId>
            <type>embedded</type>
            <log>${project.build.directory}/cargo.log</log>
            <output>${project.build.directory}/cargo.log</output>
            <logLevel>debug</logLevel>
          </container>
          <configuration>
            <properties>
              <cargo.servlet.port>8081</cargo.servlet.port>
              <cargo.logging>high</cargo.logging>
            </properties>
          </configuration>
          <deployables>
            <deployable>
              <location>${project.build.directory}/${project.build.finalName}.${project.packaging}</location>
              <type>war</type>
            </deployable>
          </deployables>
         </configuration>
	  </plugin>-->
    </plugins>
  </build>
</project>
